name: My Workflow

on: [push]

jobs:
  codeball_review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Codeball AI Code Review
        uses: sturdy-dev/codeball-action@v2.6.0
